### ISSUE TITLE
Currying

### ISSUE THREAD

**Issue by iamrecursion** [luna/enso#18]
### Summary
Currying brings a very natural way of using functions to many functional programming languages, and curried-by-default languages can be seen as more expressive than other languages. For Enso, however, the curring is even more crucial, as it allows for building complex pipelines in a very simple manner. 

However, the interaction with named and defaulted function arguments is crucial; we can't just desugar code to single-argument functions as this would mean that a given function would have no knowledge of its arguments and their names beyond the first. 

### Specification

- The enso interpreter supports curried function application and curried function passing.
- Currying interacts appropriately with named and defaulted arguments, with functions being able to be queried for their argument names and default values.
- Functions should not default to taking a single argument like in Haskell. 

### Acceptance Criteria & Test Cases

- Curried functions work and interact well with named and defaulted arguments.
- They are rigorously tested and benchmarked.
- Performance of using curried functions is equivalent to performance of calling the same functions with explicit argument passing. In other words, there is no performance difference.

**Comment by iamrecursion** [comment]
Open questions:

- When should arguments be evaluated on partially-applied functions?
- Should `_.foo bar` be equivalent to `x -> x.foo bar`? In such a case, then the arguments aren't evaluated until the lambda is called.

**Comment by kustosz** [comment]
Answers for questions above:
1. Arguments for curried (also when arguments are being passed by name) calls are always immediately evaluated. In other words, whether we have provided all the function arguments or only some of them, does not change the call semantics.
2. Yes, any occurence of `_` (also in non-self positions, such `foo bar _ baz`) is equivalent to a lambda. As such, the `_` pattern should not be implemented as part of this task – it should be handled as a static analysis / desugaring step before entering actual truffle execution and is best postponed until we start using the final parser.
