### ISSUE TITLE
Named and Defaulted Function Arguments

### ISSUE THREAD

**Issue by iamrecursion** [luna/enso#20]
### Summary
A big part of making usable scientific and data-analysis libraries is the availability and use of named and defaulted function arguments. Take a `circle` function, for instance. It may take a position and a radius as follows `mkCircle : Position -> Radius -> Circle`, but it could also take many more specialist arguments. For the people that don't care about this additional power, we want them to just be able to create a circle. 

This is where named and default arguments come in. Say, for example, that the `circle` function defaults `position = {0, 0}` and `radius = 1`. This means that a user can just create a circle by calling `circle`. Named arguments, then, allow users to change just the defaults that they want: `circle (radius = 10)`, or `circle (position = {1, 1})`. 

Support for these is instrumental to the usability of Enso for data processing.

### Specification

- The Enso interpreter has support for named arguments.
- The Enso interpreter has support for defaulted arguments.

### Acceptance Criteria & Test Cases

- Function application using defaulted or named arguments doesn't compromise on performance.
- This functionality is rigorously tested and benchmarked.

**Comment by kustosz** [comment]
Do make sure it is not conflicting with dynamic dispatch. The default arguments in general should not be considered for dispatch, complicating things quite a bit.

**Comment by iamrecursion** [comment]
A few notes on design:

- When should arguments be evaluated?
- Needs to do clever lookup in the context of dynamic dispatch.
- Should cache argument positions where possible. This can be done using reference equality on arguments and function objects.
- Need to support the use case of not using a defaulted argument (dummy syntax).

**Comment by iamrecursion** [comment]
The initial parser implementation turned out not to work, so is being re-written in order to allow named args to work properly.

**Comment by iamrecursion** [comment]
Parser has been re-written. Now working on re-building standard arguments on the new model before working with named and defaulted ones.

**Comment by iamrecursion** [comment]
All argument information is now to the call site, all that remains is to marry the definition arguments and call arguments up.

**Comment by iamrecursion** [comment]
This now works. Needs some optimisation though.

**Comment by iamrecursion** [comment]
This is now feature-complete for this task, but needs some refactoring and commenting.
