### ISSUE TITLE
Parser Precedence Shuffle

### ISSUE THREAD

**Issue by wdanilo** [luna/enso#36]
### Summary & Specification 
The first parser pass consumes the input to a chain of `Apps` without taking in consideration operator precedences, whitespace precedences, nor mixfix operators, like `if_then_els` or `(_)`. Precedence shuffling is an operation which inspects the produced AST and transforms it by applying precedence rules.

### Value
Correctly parsed precedences.

### Acceptance Criteria & Test Cases
Correctly parsed precedences.

**Comment by sylwiabr** [comment]
Can you provide a description of how to use parser and link to documentation/API description? @wdanilo

**Comment by wdanilo** [comment]
@sylwiabr sorry for not providing that. Currently there is no doc yet, but you can observe the API in the tests, especially in the "Expressions" section here: https://github.com/luna/enso/blob/parser/syntax/specialization/src/test/scala/org/enso/syntax/text/Parser.scala 

Before I make the final parser PR I'll add suitable docs.

**Comment by sylwiabr** [comment]
Ok so I will wait with acceptance for that.

**Comment by sylwiabr** [comment]
@wdanilo how can I test this?
