### ISSUE TITLE
Implement Parser Special Constructs

### ISSUE THREAD

**Issue by wdanilo** [luna/enso#37]
### Summary
Based on the parser framework, it's important to implement special constructs, like `type` definitions. These constructs could be in the future implemented using the meta-enso layer, so here we need to use the same layer, but internally.

### Value
Correct parsing of all Enso constructs.

### Acceptance Criteria & Test Cases
All language constructs should be parsed correctly.

**Comment by sylwiabr** [comment]
Is there a PR @wdanilo ? If so, please connect it to the issue.

**Comment by sylwiabr** [comment]
@wdanilo how can I test it?
