### ISSUE TITLE
Rename File Manager Project

### ISSUE THREAD

**Issue by iamrecursion** [luna/enso#63]
### Summary
The file manager folder in the repo doesn't match the naming convention of the rest, which is `lowercase-kebab-case`. It should be renamed to `file-manager` for consistency with the rest of the project structure. 

### Specification

- Rename the `FileManager` folder to `file-manager`.

### Acceptance Criteria & Test Cases

- The above is done and all the tests pass.

**Comment by mwu-tow** [comment]
When discussed during CR @wdanilo suggested renaming the folder to CamelCase to improve consistence.
I was supposed to file a PR for guidelines suggesting the CamelCase convention and adjusting other projects. Will do that later today. Whatever will be decided in that matter — yes, folder names should be unified.

**Comment by iamrecursion** [comment]
Okay, sounds good. I have a preference for `kebab-case`, but it isn't a particularly strong one.

**Comment by mwu-tow** [comment]
Issue obsoleted by #64.
