### ISSUE TITLE
Review the Names and Documentation in the Enso Protocol Specification

### ISSUE THREAD

**Issue by mwu-tow** [luna/enso#708]
### Summary
While reviewing client implementations for enso-protocol (in the ide repo), @wdanilo raised a number of concerns about names of entities in the protocol and the documentation provided.

See some discussions in 
https://github.com/luna/ide/pull/366
https://github.com/luna/ide/pull/391

For now, we've decided against taking any action as part of client implementation task, as:
1) protocol is owned by the engine team;
2) we do not have time for this.

However, I'm leaving this as a task to allow us to plan for investing work in improving the naming in the protocol.

### Value
Nicer code potentially.

### Specification
Organize a discussion between stakeholders (specification owner, client owner, Wojciech) to discuss the desired changes and introduce them.

### Acceptance Criteria & Test Cases
Stakeholders are happy.

**Comment by iamrecursion** [comment]
@4e6 @lolczak please take a look at this and make a decision if we want to change naming in light of the concerns raised.

**Comment by kustosz** [comment]
I only see one, pertaining to @wdanilo favoring `Unrecognized` over `Other` in the file system API. I disagree – the message does not mean `Unrecognized` – we might as well know exactly what that is and decide not to disclose that (e.g. for security reasons).
Is there anything else in these discussions?

**Comment by mwu-tow** [comment]
> I only see one, pertaining to @wdanilo favoring Unrecognized over Other in the file system API. I disagree – the message does not mean Unrecognized – we might as well know exactly what that is and decide not to disclose that (e.g. for security reasons).

The problem here is that protocol specification states that `Other` serves to "Represents unrecognized object.". If the object is unrecognized, it should be accordingly named. If `Other` might be recognized, it should be described in a different way.

>  Is there anything else in these discussions?

Some typenames, most relevantly `Path`.

Considering rename project picker -> project manager (picker doesn't really sound like something that manages multiple, potentially overlapping project lifetimes).

Also, documentation is in many places inconsistent or fluffy (I mean here just repeating the identifier words) while not providing a potentially useful information. 

For example, `DirectoryTruncated` is said to be `a directory which contents have been truncated`. But user of this type has no idea what "truncating" means. When I call `file/create` to create a new, empty directory, should I use `DirectoryTruncated`? Likely not — but I have no idea what would that even mean and I don't really think it should be expressible.

The only other mention of truncating is in `file/tree` method description but it is called a "flag" and the `FileSystemObject` doesn't have this as flag and is also used in other methods.

And likely similar.
