### ISSUE TITLE
Parser AST Zippers stub

### ISSUE THREAD

**Issue by wdanilo** [luna/enso#71]
### Summary
AST should have provide a zipper (https://wiki.haskell.org/Zipper) for AST location manipulation.

### Value
Being able to efficiently mark paths inside AST for GUI - backend communication and synchronisation.

### Specification
This task is more a research task than a real implementation. We need to design the proper way of expressing a zipper for our AST. We should consider different approaches, including using Shapeless abstraction.

### Acceptance Criteria & Test Cases
Agreement regarding the Zipper look and feel, discussed with @mwu-tow and @kustosz .

**Comment by sylwiabr** [comment]
@kustosz @mwu-tow did you agree? What was the conclusion? @wdanilo please sum up the discussion.

**Comment by wdanilo** [comment]
We came to a conclusion that for now we do not need zippers, so this task was canceled. Closing it for now!
