### ISSUE TITLE
GH Pages for Internal Docs

### ISSUE THREAD

**Issue by joenash** [luna/enso#747]
### Summary
The structure of the [docs](https://github.com/luna/enso/tree/master/doc) makes it difficult to edit and update. In an ideal world, the files would be much smaller, rather than monolithic files composed of many sections. Within the repo though, this is at conflict with readability. To land somewhere in the middle, we're going to take advantage of GitHub Pages to render the docs in a readable webpage, allowing @iamrecursion to structure the actual `.md` files into iddy biddy bitesize chunks. 

Ara's wishlist:
- Minimal theme with Enso logo
- Main page is enso-philosophy.md
- TOC always comes from README.md in each folder
- TOC on main page links to sub-docs
- TOC on sub-docs (one for each `doc/$folder`) in the sidebar
- Link back to "Home" somewhere

Joe's notes:
- Will probably require some minimal Jekyll edits for the TOC, so will need to add some assets to the `/docs` folder. 
- Would also like a page that traverses the entire `doc` and subfolders and renders the docs in one page, for ease of reading/search/traversal. Though perhaps the need for this could also be met by a searchbar. 

### Value
- Easy to maintain, easy to read
- Nicer urls for linking, i.e. can be something like dev.enso.org/syntax/specification 
- A nice experiment in a possible way to maintain the user docs in future, that makes them a good target for external contributions.

**Comment by iamrecursion** [comment]
I'd love both a scrollable one-pager version _and_ a search bar, if you can do both!

**Comment by iamrecursion** [comment]
Love the way the [mermaid](https://mermaid-js.github.io/mermaid/#/) sidebar works.

**Comment by iamrecursion** [comment]
Support for dark/light mode via CSS media query.

Should be hosted at `https://dev.enso.org`.

**Comment by iamrecursion** [comment]
At the top right we should link to the github organisation, and the main [enso.org](https://enso.org) site.

**Comment by joenash** [comment]
Progress update:
- Minimal theme with Enso logo
  - We opted for the gitbook theme in the end. No Enso logo yet. 
- Main page is enso-philosophy.md
  - There was some rethinking here: mainpage of the site yet to be determined
- TOC always comes from README.md in each folder
   - TOC comes from files in directory, using the "order" field in the frontmatter.
- TOC on main page links to sub-docs
   - ✅ 
- TOC on sub-docs (one for each `doc/$folder`) in the sidebar
  - ✅, I think? Sidebar toc currently shows files in current directory level, and then titles from README's in any subdirectories. 
- Link back to "Home" somewhere
   - ✅ 
- I'd love both a scrollable one-pager version and a search bar, if you can do both!
   - Search bar in via Algolia. No complete one pager yet.
- Support for dark/light mode via CSS media query.
  - gitbook theme has a dark mode, I need to hook it up to the media query. Also note that the Algolia styled search bar doesn't toggle dark mode with the dark/light switcher button on the theme, I need to fix that.
- Should be hosted at https://dev.enso.org.
   - ✅ 
- At the top right we should link to the github organisation, and the main enso.org site.
  - Not yet, will remove the social media buttons and add this.

**Comment by joenash** [comment]
Now that the site is up and usable, closing this issue in favour of issues in its own repo.
