### ISSUE TITLE
VisualisationEvaluationError should be delivered via binary protocol

### ISSUE THREAD

**Issue by lolczak** [luna/enso#785]
Please define the binary error and route these errors to the binary connection controller.

### General Summary
When an error occurs during the evaluation of visualization code, the error message is not delivered to a client.

### Steps to Reproduce

1. Attach visualization with expression `a->a.to_string`
2. Execute context with the attached visualization

### Expected Result
The VisualisationEvaluationError should be emitted via the binary protocol.

### Actual Result
Lack of error on both channels.

### Enso Version
All

**Comment by kustosz** [comment]
Please note the above concerns evaluating the visualization on an actual expression value, not the compilation of the visualization expression (which is done during attaching the visualization and should be reported as an error response to the `attachVisualization` message, on the RPC pipe).
